userName=hrm_user

password=Hrm_user@123

url=https://www.syntaxhrm.com/web/index.php/auth/login

browser=Chrome

viewSystemUsersUrl=viewSystemUsers

headless=true

dbURL=jdbc:mysql://148.72.132.33:3307/syntax_hrm

dbUsername=syntax_std

dbPassword=syntax_std@2026
